//../regolith/_port/packer_320_480_full
//Fri Jan 18 15:19:11 MSK 2013 , version: 108

package com.geargames.regolith.app;

public class Graph {


    final static public byte IMG_COUNT = 18;
    final static public byte ELEMENT_LINE = 18;
    final static public byte ELEMENT_RECT = 19;
    final static public byte ELEMENT_FILLRECT = 20;
    final static public byte ELEMENT_FILLRECT_x4 = 21;
    final static public byte ELEMENT_ARC = 22;
    final static public int FRAMES_COUNT = 798;
    final static public int SPR_COUNT = 270;
    final static public int ANIM_COUNT = 1;
    final static public int UNIT_COUNT = 427;
    final static public int UNITS_COUNT = 125;
    final static public int AFFINES_COUNT = 31;
//Image
//Frame
    final static public byte EL_EMPTY = 0;
    final static public byte MAN_1_DIR_1_BODY = 2;
    final static public byte MAN_1_DIR_2_BODY = 9;
    final static public byte MAN_1_DIR_3_BODY = 16;
    final static public byte MAN_1_DIR_4_BODY = 22;
    final static public byte MAN_1_DIR_1_HEAD = 29;
    final static public byte MAN_1_DIR_2_HEAD = 32;
    final static public byte MAN_1_DIR_3_HEAD = 36;
    final static public byte MAN_1_DIR_4_HEAD = 40;
    final static public byte MAN_1_DIR_1_FOOT = 44;
    final static public byte MAN_1_DIR_2_FOOT = 80;
    final static public byte MAN_1_DIR_3_FOOT = 122;
    final static public short MAN_1_DIR_4_FOOT = 165;
    final static public short MAN_1_DIR_1_ARM = 201;
    final static public short MAN_1_DIR_2_ARM = 231;
    final static public short MAN_1_DIR_3_ARM = 282;
    final static public short MAN_1_DIR_4_ARM = 325;
    final static public short MAN_1_DIR_1_WEAPON = 371;
    final static public short MAN_1_DIR_2_WEAPON = 375;
    final static public short MAN_1_DIR_3_WEAPON = 387;
    final static public short MAN_1_DIR_4_WEAPON = 405;
    final static public short EL_FONT = 684;
//Sprite
    final static public byte SPR_EMPTY = 0;
    final static public byte SPR_GROUND = 1;
    final static public byte SPR_BOTTON = 2;
    final static public byte SPR_PICTURE_BACK = 12;
    final static public byte SPR_TEST = 13;
    final static public byte SPR_PANEL_BACK = 16;
    final static public byte SPR_PANEL_FRAME = 28;
    final static public byte SPR_SUB_PANEL = 35;
    final static public byte SPR_SIDE = 37;
    final static public byte SPR_PANEL_TOP_LEFT = 41;
    final static public byte SPR_PANEL_TOP_CENTRE = 42;
    final static public byte SPR_PANEL_TOP_RIGHT = 43;
    final static public byte SPR_TEAM_COLOR = 51;
    final static public byte SPR_SKILL_ICO = 58;
    final static public byte SPR_CHARACTER_IND = 66;
    final static public byte SPR_SKILL_IND = 77;
    final static public byte SPR_ICO_LIFE_IND = 98;
    final static public byte SPR_BUTTON = 106;
    final static public short SPR_ICO_WEAPON = 155;
    final static public short SPR_TEXT_TEST = 169;
    final static public short SPR_FONT_SYMB = 171;
    final static public short SPR_FONT_NUM = 187;
    final static public short SPR_FONT_EN = 204;
    final static public short SPR_FONT_RU = 236;
//Animation
//Unit
    final static public byte U_MAN_IDLE_old = 0;
    final static public byte U_MAN_FIRE_AUTO = 8;
    final static public byte U_MAN_HIT = 24;
    final static public byte U_MAN_IDLE = 32;
    final static public byte U_MAN_RUN_1 = 33;
    final static public byte U_MAN_RUN_RIFLE_DIR_1 = 35;
    final static public byte U_MAN_RUN_PISTOL_DIR_1 = 43;
    final static public byte U_MAN_RUN_SHOTGUN_DIR_1 = 51;
    final static public byte U_MAN_STAY_KNIFE_2 = 59;
    final static public byte U_MAN_STAY_FIST_2 = 62;
    final static public byte U_MAN_HIT_FIST_2 = 67;
    final static public byte U_MAN_STAY_PISTOL_2 = 70;
    final static public byte U_MAN_HIT_PISTOL_2 = 75;
    final static public byte U_MAN_DOWN_PISTOL_2 = 78;
    final static public byte U_MAN_STAY_RIFLE_2 = 85;
    final static public byte U_MAN_HIT_RIFLE_2 = 91;
    final static public byte U_MAN_DOWN_RIFLE_2 = 94;
    final static public byte U_MAN_STAY_SHOTGUN_2 = 101;
    final static public byte U_MAN_HIT_SHOTGUN_2 = 106;
    final static public byte U_MAN_DOWN_SHOTGUN_2 = 109;
    final static public byte U_MAN_HIT_LAUNCHER_2 = 116;
    final static public byte U_MAN_STAY_LAUNCHER_2 = 119;
    final static public short U_MAN_DOWN_LAUNCHER_2 = 128;
    final static public short U_MAN_STAY_GRENADE_2 = 137;
    final static public short U_MAN_RUN_FIST_2 = 145;
    final static public short U_MAN_RUN_KNIFE_2 = 153;
    final static public short U_MAN_RUN_PISTOL_2 = 154;
    final static public short U_MAN_RUN_RIFLE_2 = 162;
    final static public short U_MAN_RUN_SHOTGUN_2 = 170;
    final static public short U_MAN_STAY_LAUNCHER_3 = 178;
    final static public short U_MAN_RUN_FIST_3 = 188;
    final static public short U_MAN_SHOT_FIST_3 = 196;
    final static public short U_MAN_HIT_FIST_3 = 201;
    final static public short U_MAN_RUN_PISTOL_3 = 204;
    final static public short U_MAN_SHOT_PISTOL_3 = 212;
    final static public short U_MAN_DOWN_PISTOL_3 = 217;
    final static public short U_MAN_HIT_PISTOL_3 = 223;
    final static public short U_MAN_RUN_RIFLE_3 = 226;
    final static public short U_MAN_SHOT_RIFLE_3 = 234;
    final static public short U_MAN_HIT_RIFLE_3 = 239;
    final static public short U_MAN_DOWN_RIFLE_3 = 242;
    final static public short U_MAN_RUN_SHOTGUN_3 = 247;
    final static public short U_MAN_SHOT_SHOTGUN_3 = 255;
    final static public short U_MAN_DOWN_SHOTGUN_3 = 259;
    final static public short U_MAN_HIT_SHOTGUN_3 = 264;
    final static public short U_MAN_RUN_LAUNCHER_3 = 267;
    final static public short U_MAN_SHOT_LAUNCHER_3 = 275;
    final static public short U_MAN_DOWN_LAUNCHER_3 = 280;
    final static public short U_MAN_HIT_LAUNCHER_3 = 286;
    final static public short U_MAN_SHOT_GRENAD_3 = 289;
    final static public short U_MAN_RUN_FIST_DIR_4 = 294;
    final static public short U_MAN_SHOT_FIST_DIR_4 = 302;
    final static public short U_MAN_HIT_RIFLE_DIR_4 = 306;
    final static public short U_MAN_RUN_RIFLE_DIR_4 = 310;
    final static public short U_MAN_SHOT_RIFLE_4 = 318;
    final static public short U_MAN_DOWN_RIFLE_4 = 322;
    final static public short U_MAN_HIT_RIFLE_4 = 327;
    final static public short U_MAN_RUN_PISTOL_4 = 331;
    final static public short U_MAN_SHOT_PISTOL_4 = 339;
    final static public short U_MAN_DOWN_PISTOL_4 = 344;
    final static public short U_MAN_HIT_PISTOL_4 = 350;
    final static public short U_MAN_RUN_SHOTGUN_4 = 356;
    final static public short U_MAN_SHOT_SHOTGUN_4 = 364;
    final static public short U_MAN_DOWN_SHOTGUN_4 = 368;
    final static public short U_MAN_HIT_SHOTGUN_4 = 373;
    final static public short U_MAN_RUN_LAUNCHER_4 = 376;
    final static public short U_MAN_SHOT_LAUNCHER_4 = 384;
    final static public short U_MAN_DOWN_LAUNCHER_4 = 389;
    final static public short U_MAN_HIT_LAUNCHER_4 = 395;
    final static public short U_MAN_SHOT_GRENADE_3 = 398;
    final static public short U_MAN_HIT_FIST_4 = 402;
    final static public short U_MAN_RUN_DAGGER_1 = 403;
    final static public short U_MAN_SHOOT_PISTOL = 406;
    final static public short U_MAN_SHOOT_SHOTGUN = 409;
    final static public short U_MAN_HIT_5 = 415;
    final static public short U_MAN_GRENADE = 417;
//Unit script
    final static public byte UN_MAN_IDLE = 0;
    final static public byte UN_MAN_WALK = 8;
    final static public byte UN_MAN_FIRE_AUTO = 16;
    final static public byte UN_MAN_HIT = 24;
    final static public byte UN_MAN_RUN_1_2 = 32;
    final static public byte UN_MAN_RUN_RIFLE_1 = 33;
    final static public byte UN_MAN_RUN_PISTOL_1 = 34;
    final static public byte UN_MAN_RUN_SHOTGUN_1 = 35;
    final static public byte UN_MAN_RUN = 36;
    final static public byte UN_MAN_RUN_FIST_2 = 37;
    final static public byte UN_MAN_RUN_KNIFE_2 = 38;
    final static public byte UN_MAN_RUN_PISTOL_2 = 39;
    final static public byte UN_MAN_RUN_RIFLE_2 = 40;
    final static public byte UN_MAN_RUN_SHOTGUN_2 = 41;
    final static public byte UN_MAN_RUN_LAUNCHER_2 = 42;
    final static public byte UN_MAN_SHOT_FIST_2 = 43;
    final static public byte UN_MAN_SHOT_PISTOL_2 = 44;
    final static public byte UN_MAN_DOWN_PISTOL_2 = 45;
    final static public byte UN_MAN_DOWN_SHOT_PISTOL_2 = 46;
    final static public byte UN_MAN_UP_PISTOL_2 = 47;
    final static public byte UN_MAN_SHOT_RIFLE_2 = 48;
    final static public byte UN_MAN_DOWN_RIFLE_2 = 49;
    final static public byte UN_MAN_DOWN_SHOT_RIFLE_2 = 50;
    final static public byte UN_MAN_UP_RIFLE_2 = 51;
    final static public byte UN_MAN_SHOT_SHOTGUN_2 = 52;
    final static public byte UN_MAN_DOWN_SHOTGUN_2 = 53;
    final static public byte UN_MAN_DOWN_SHOT_SHOTGUN_2 = 54;
    final static public byte UN_MAN_UP_SHOTGUN_2 = 55;
    final static public byte UN_MAN_SHOT_LAUNCHER_2 = 56;
    final static public byte UN_MAN_DOWN_LAUNCHER_2 = 57;
    final static public byte UN_MAN_DOWN_SHOT_LAUNCHER_2 = 58;
    final static public byte UN_MAN_UP_LAUNCHER_2 = 59;
    final static public byte UN_MAN_HIT_FIST_2 = 60;
    final static public byte UN_MAN_HIT_PISTOL_2 = 61;
    final static public byte UN_MAN_HIT_RIFLE_2 = 62;
    final static public byte UN_MAN_HIT_SHOTGUN_2 = 63;
    final static public byte UN_MAN_HIT_LAUNCHER_2 = 64;
    final static public byte UN_MAN_SHOT_GRENADE_2 = 65;
    final static public byte UN_MAN_RUN_FIST_3 = 67;
    final static public byte UN_MAN_SHOT_FIST_3 = 68;
    final static public byte UN_MAN_RUN_PISTOL_3 = 69;
    final static public byte UN_MAN_SHOT_PISTOL_3 = 70;
    final static public byte UN_MAN_DOWN_PISTOL_3 = 71;
    final static public byte UN_MAN_DOWN_SHOT_PISTOL_3 = 72;
    final static public byte UN_MAN_UP_PISTOL_3 = 73;
    final static public byte UN_MAN_RUN_RIFLE_3 = 74;
    final static public byte UN_MAN_DOWN_RIFLE_3 = 75;
    final static public byte UN_MAN_DOWN_SHOT_RIFLE_3 = 76;
    final static public byte UN_MAN_UP_RIFLE_3 = 77;
    final static public byte UN_MAN_SHOT_RIFLE_3 = 78;
    final static public byte UN_MAN_RUN_SHOTGUN_3 = 79;
    final static public byte UN_MAN_SHOT_SHOTGUN_3 = 80;
    final static public byte UN_MAN_DOWN_SHOTGUN_3 = 81;
    final static public byte UN_MAN_DOWN_SHOT_SHOTGUN_3 = 82;
    final static public byte UN_MAN_UP_SHOTGUN_3 = 83;
    final static public byte UN_MAN_RUN_LAUNCHER_3 = 84;
    final static public byte UN_MAN_SHOT_LAUNCHER_3 = 85;
    final static public byte UN_MAN_DOWN_LAUNCHER_3 = 86;
    final static public byte UN_MAN_DOWN_SHOT_LAUNCHER_3 = 87;
    final static public byte UN_MAN_UP_LAUNCHER_3 = 88;
    final static public byte UN_MAN_HIT_FIST_3 = 89;
    final static public byte UN_MAN_HIT_PISTOL_3 = 90;
    final static public byte UN_MAN_HIT_RIFLE_3 = 91;
    final static public byte UN_MAN_HIT_SHOTGUN_3 = 92;
    final static public byte UN_MAN_HIT_LAUNCHER_3 = 93;
    final static public byte UN_MAN_SHOT_GRENADE_3 = 94;
    final static public byte UN_MAN_RUN_FIST_4 = 96;
    final static public byte UN_MAN_SHOT_FIST_4 = 97;
    final static public byte UN_MAN_HIT_FIST_4 = 98;
    final static public byte UN_MAN_RUN_RIFLE_4 = 99;
    final static public byte UN_MAN_SHOT_RIFLE_4 = 100;
    final static public byte UN_MAN_DOWN_RIFLE_4 = 101;
    final static public byte UN_MAN_DOWN_SHOT_RIFLE_4 = 102;
    final static public byte UN_MAN_UP_RIFLE_4 = 103;
    final static public byte UN_MAN_HIT_RIFLE_4 = 104;
    final static public byte UN_MAN_RUN_PISTOL_4 = 105;
    final static public byte UN_MAN_SHOT_PISTOL_4 = 106;
    final static public byte UN_MAN_DOWN_PISTOL_4 = 107;
    final static public byte UN_MAN_DOWN_SHOT_PISTOL_4 = 108;
    final static public byte UN_MAN_UP_PISTOL_4 = 109;
    final static public byte UN_MAN_HIT_PISTOL_4 = 110;
    final static public byte UN_MAN_RUN_SHOTGUN_4 = 111;
    final static public byte UN_MAN_SHOT_SHOTGUN_4 = 112;
    final static public byte UN_MAN_DOWN_SHOTGUN_4 = 113;
    final static public byte UN_MAN_DOWN_SHOT_SHOTGUN_4 = 114;
    final static public byte UN_MAN_UP_SHOTGUN_4 = 115;
    final static public byte UN_MAN_HIT_SHOTGUN_4 = 116;
    final static public byte UN_MAN_RUN_LAUNCHER_4 = 117;
    final static public byte UN_MAN_SHOT_LAUNCHER_4 = 118;
    final static public byte UN_MAN_DOWN_LAUNCHER_4 = 119;
    final static public byte UN_MAN_DOWN_SHOT_LAUNCHER_4 = 120;
    final static public byte UN_MAN_UP_LAUNCHER_4 = 121;
    final static public byte UN_MAN_HIT_LAUNCHER_4 = 122;
    final static public byte UN_MAN_SHOT_GRENADE_4 = 123;
//Object
    final static public byte OBJ_FENCE = 0;
    final static public byte OBJ_BAR = 4;
    final static public byte PAN_MAIN_MENU = 6;
    final static public byte PAN_TYPE_BATTLE = 7;
    final static public byte PAN_FIGHTER = 8;
    final static public byte PAN_FIGHTER_INFO = 9;
    final static public byte PAN_WEAPON_SELECT = 10;
    final static public byte PAN_BATTLE_LIST = 11;
    final static public byte PAN_BATTLE_CREATE = 12;
    final static public byte PAN_PLAYER_INFO = 13;
    final static public byte PAN_FIGHTER_SELECT = 14;
    final static public byte PAN_LEFT = 15;
    final static public byte PAN_CENTER = 16;
    final static public byte PAN_RIGHT = 17;
    final static public byte OBJ_SUBPANEL_WEAPON_LEFT = 18;
    final static public byte OBJ_LIST_WEAPON_ITEM = 19;
    final static public byte OBJ_LIST_BATTLE_ITEM = 20;
    final static public byte OBJ_LIST_WEAPON = 21;
    final static public byte OBJ_LIST_BATTLE = 22;
    final static public byte OBJ_LIST_FIGHTER = 23;
    final static public byte OBJ_LIST_REWARD = 24;
    final static public byte OBJ_LIST_FIGHTER_FACE = 25;
    final static public byte OBJ_REWARD_AVA_BIG = 26;
    final static public byte OBJ_PLAYER_AVA_BIG = 27;
    final static public byte OBJ_PLAYER_AVA_SMALL = 28;
    final static public byte OBJ_FIGHTER_SMALL = 29;
    final static public byte OBJ_SIDE = 30;
    final static public byte OBJ_BATTLE = 34;
    final static public byte OBJ_IND_HEALTH = 35;
    final static public byte OBJ_IND_1 = 36;
    final static public byte OBJ_IND_CHARACTER = 37;
    final static public byte OBJ_IND_SKILL = 38;
    final static public byte OBJ_LABEL_MONEY = 39;
    final static public byte OBJ_BUT_LATER = 40;
    final static public byte OBJ_BUT_PREVISION = 41;
    final static public byte OBJ_BUT_BACK = 42;
    final static public byte OBJ_BUT_RADIO = 43;
    final static public byte OBJ_BUT = 53;
    final static public byte OBJ_BUT_SELECT = 54;
    final static public byte OBJ_BUT_BATTLE = 56;
    final static public byte OBJ_BUT_KICK = 57;
    final static public byte OBJ_BUT_PLAYER_INFO = 62;
    final static public byte OBJ_BUT_WIEW = 64;
    final static public byte OBJ_BUT_PLUS = 66;
    final static public byte OBJ_SPINBOX = 68;
    final static public byte MENU_COMMON = 69;
    final static public byte MENU_COMMON_ITEM = 70;
    final static public byte MENU_COMMON_CONFIRM = 71;
    final static public byte MENU_BOTTON_YES = 72;
    final static public byte MENU_BOTTON_NO = 73;
    final static public byte MENU_BOTTON_MENU = 74;
    final static public byte MENU_TEST = 75;
    final static public byte MENU_TEST_2 = 76;
    final static public byte OBJ_PANEL_TOP_TEST = 77;
//Location
//Map
//PColor
//GAI
//Mission
     final static int[] COLOR = {0, 65535, };
    static public int getCOLOR(int i){return COLOR[i];};

//Links
    final static public byte Frame_I_ID = 0;//798
    final static public byte Frame_I_TYPE = 1;//798
    final static public byte Sprite_index_I_TYPE = 2;//1056
    final static public byte Animation_index_I_TYPE = 3;//1
    final static public byte Unit_index_I_TYPE = 4;//4045
    final static public byte Unit_index_I_H = 5;//4045
    final static public byte Unit_script_index_I_TYPE = 6;//1010
    final static public byte Object_index_I_W = 7;//413
    final static public byte Object_index_I_H = 8;//413
    final static public byte Object_index_I_TYPE = 9;//413
    final static public byte Object_index_I_LAYER_TYPE = 10;//413
    final static public byte Object_index_I_SLOT = 11;//413
    final static public byte Emitter_index_I_W = 12;//0
    final static public byte Emitter_index_I_H = 13;//0
    final static public byte Emitter_index_I_TYPE = 14;//0
    final static public byte Emitter_index_I_SLOT = 15;//0
    final static public byte Affine_I_AF_TR = 16;//31
    final static public byte Affine_I_AF_SC_X = 17;//31
    final static public byte Affine_I_AF_SC_Y = 18;//31
    final static public byte Affine_I_AF_HM = 19;//31
    final static public byte Affine_I_AF_VM = 20;//31
    final static public byte PARAM_BYTE_COUNT = 21;

    final static public byte Frame_I_X = 21;//798
    final static public byte Frame_I_Y = 22;//798
    final static public byte Frame_I_W = 23;//798
    final static public byte Frame_I_H = 24;//798
    final static public byte Sprite_I_X = 25;//270
    final static public byte Sprite_I_Y = 26;//270
    final static public byte Sprite_index_I_ID = 27;//1056
    final static public byte Sprite_index_I_X = 28;//1056
    final static public byte Sprite_index_I_Y = 29;//1056
    final static public byte Animation_I_X = 30;//1
    final static public byte Animation_I_Y = 31;//1
    final static public byte Animation_index_I_ID = 32;//1
    final static public byte Animation_index_I_X = 33;//1
    final static public byte Animation_index_I_Y = 34;//1
    final static public byte Unit_I_X = 35;//427
    final static public byte Unit_I_Y = 36;//427
    final static public byte Unit_index_I_ID = 37;//4045
    final static public byte Unit_index_I_X = 38;//4045
    final static public byte Unit_index_I_Y = 39;//4045
    final static public byte Unit_script_I_X = 40;//125
    final static public byte Unit_script_I_Y = 41;//125
    final static public byte Unit_script_index_I_ID = 42;//1010
    final static public byte Unit_script_index_I_X = 43;//1010
    final static public byte Unit_script_index_I_Y = 44;//1010
    final static public byte Object_I_X = 45;//78
    final static public byte Object_I_Y = 46;//78
    final static public byte Object_index_I_ID = 47;//413
    final static public byte Object_index_I_X = 48;//413
    final static public byte Object_index_I_Y = 49;//413
    final static public byte Emitter_I_X = 50;//0
    final static public byte Emitter_I_Y = 51;//0
    final static public byte Emitter_index_I_ID = 52;//0
    final static public byte Emitter_index_I_X = 53;//0
    final static public byte Emitter_index_I_Y = 54;//0
    final static public byte Affine_I_X = 55;//31
    final static public byte Affine_I_Y = 56;//31
    final static public byte Affine_I_AF_RO = 57;//31
    final static public byte Affine_index_I_ID = 58;//31
    final static public byte Affine_index_I_X = 59;//31
    final static public byte Affine_index_I_Y = 60;//31
    final static public byte PARAM_SHORT_COUNT = 40;

    final static public byte Emitter_I_EM0 = 61;//0
    final static public byte Emitter_I_EM1 = 62;//0
    final static public byte Emitter_I_EM2 = 63;//0
    final static public byte Emitter_I_EM3 = 64;//0
    final static public byte Emitter_I_EM4 = 65;//0
    final static public byte Emitter_I_EM5 = 66;//0
    final static public byte Emitter_I_EM6 = 67;//0
    final static public byte Emitter_I_EM7 = 68;//0
    final static public byte Emitter_I_EM8 = 69;//0
    final static public byte Emitter_I_EM9 = 70;//0
    final static public byte Emitter_I_EM10 = 71;//0
    final static public byte Emitter_I_EM11 = 72;//0
    final static public byte Emitter_I_EM12 = 73;//0
    final static public byte Emitter_I_EM13 = 74;//0
    final static public byte Emitter_I_EM14 = 75;//0
    final static public byte Emitter_I_EM15 = 76;//0
    final static public byte Emitter_I_EM16 = 77;//0
    final static public byte Emitter_I_EM17 = 78;//0
    final static public byte Emitter_I_EM18 = 79;//0
    final static public byte Emitter_I_EM19 = 80;//0
    final static public byte PARAM_INT_COUNT = 20;
    final static public int PARAM_MAX_SIZE = 4045;//getCount of maximum array

//structure of packeting images
     final static byte[] IMG_INDEX = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    static public int getIMG_INDEX(int i) {
        return IMG_INDEX[i];
    };
     final static int[] IMG_LEN = {194729,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};


    public Graph() {
/*ObjC uncomment*///return self;
    }

}
